import '@/styles/globals.css'
import {CartProvider} from "react-use-cart";
import Head from "next/head";


export default function App({Component, pageProps}) {
	return (
		<CartProvider>
			<Head>
				<title>STIVE</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			
			
			<Component {...pageProps} />
		</CartProvider>
	)
}
