import Head from 'next/head'
import Format from "@/layout/Format";
import FilterBar from "@/components/UI/FilterBar";
import ProductRecommandation from "@/components/ProductRecommandation";
import Swiper from "@/components/UI/Swiper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Format>
        <Swiper/>
        <ProductRecommandation/>
      </Format>
      
    </>
  )
}
